services:
  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - '6379:6379'
    restart: always

  redis-insight:
    image: redis/redisinsight
    ports:
      - '5540:5540'
