version: '3.9'

services:
  blog-app:
    build: .
    container_name: blog-app

    restart: always

    ports:
      - '3000:3000'

    env_file:
      - .env.production

    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
