import { Post } from '@/types/blog'

export const posts: Post[] = [
  {
    id: '1',
    title: 'Building Scalable MERN Architecture',
    slug: 'scalable-mern-architecture',
    excerpt: 'Learn how enterprise MERN apps are structured for scale.',
    content: 'Full blog content here...',
    image: '/images/hero1.jpg',
    category: { id: '1', name: 'Architecture', slug: 'architecture' },
    createdAt: '2026-02-01',
    readingTime: '8 min read',
  },
  {
    id: '2',
    title: 'Advanced Next.js Performance Patterns',
    slug: 'nextjs-performance',
    excerpt: 'Production techniques to optimize App Router apps.',
    content: 'Full blog content here...',
    image: '/images/hero2.jpg',
    category: { id: '2', name: 'Next.js', slug: 'nextjs' },
    createdAt: '2026-02-05',
    readingTime: '6 min read',
  },
  {
    id: '1',
    title: 'Building Scalable MERN Architecture',
    slug: 'scalable-mern-architecture',
    excerpt: 'Learn how enterprise MERN apps are structured for scale.',
    content: 'Full blog content here...',
    image: '/images/hero-image.png',
    category: { id: '1', name: 'Architecture', slug: 'architecture' },
    createdAt: '2026-02-01',
    readingTime: '8 min read',
  },
  {
    id: '2',
    title: 'Advanced Next.js Performance Patterns',
    slug: 'nextjs-performance',
    excerpt: 'Production techniques to optimize App Router apps.',
    content: 'Full blog content here...',
    image: '/images/hero1.jpg',
    category: { id: '2', name: 'Next.js', slug: 'nextjs' },
    createdAt: '2026-02-05',
    readingTime: '6 min read',
  },
  {
    id: '1',
    title: 'Building Scalable MERN Architecture',
    slug: 'scalable-mern-architecture',
    excerpt: 'Learn how enterprise MERN apps are structured for scale.',
    content: 'Full blog content here...',
    image: '/images/hero2.jpg',
    category: { id: '1', name: 'Architecture', slug: 'architecture' },
    createdAt: '2026-02-01',
    readingTime: '8 min read',
  },
  {
    id: '2',
    title: 'Advanced Next.js Performance Patterns',
    slug: 'nextjs-performance',
    excerpt: 'Production techniques to optimize App Router apps.',
    content: 'Full blog content here...',
    image: '/images/hero2.jpg',
    category: { id: '2', name: 'Next.js', slug: 'nextjs' },
    createdAt: '2026-02-05',
    readingTime: '6 min read',
  },
]
